apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rcz82zm3i-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rcz82zm3i-nodejs 
  name: rcz82zm3i-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: rcz82zm3i-nodejs 
